services:
  mongodb:
    image: mongo:latest
    hostname: test_mongodb
    container_name: db
    environment:
      - MONGO_INITDB_DATABASE=condorsy
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:root

  app:
    build: .
    container_name: python_app
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://root:pass@mongodb:27017/condorsy?authSource=root

volumes:
  mongodb_data:
